# Use Node.js as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR api-service

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install -g pnpm && pnpm install

# Copy the email service code
COPY . .

# Expose the port that the API service uses
EXPOSE 4004

# Start the API service
CMD ["pnpm", "start:api"]