# Use Node.js as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR email-service

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install -g pnpm && pnpm install

# Copy the email service code
COPY . .

# Expose the port that the Email service uses
EXPOSE 3001

# Start the Email service
CMD ["pnpm", "start:email"]